//! Command for creating a source.

use shared_cqrs::command::domain::command::Command;

use crate::source::domain::value_objects::source_description::SourceDescription;
use crate::source::domain::value_objects::source_id::SourceId;
use crate::source::domain::value_objects::source_status::SourceStatus;
use crate::source::domain::value_objects::source_type::SourceType;

/// Command that requests the creation of a new source.
///
/// `created_at` / `updated_at` are intentionally **not** part of the command —
/// they are generated by [`SourceCreator`] at execution time.
///
/// [`SourceCreator`]: super::source_creator::SourceCreator
pub struct CreateSourceCommand {
    pub id: SourceId,
    pub source_type: SourceType,
    pub status: SourceStatus,
    pub description: SourceDescription,
}

impl Command for CreateSourceCommand {}
