//! Command for updating a source.

use shared_cqrs::command::domain::command::Command;

use crate::source::domain::value_objects::source_description::SourceDescription;
use crate::source::domain::value_objects::source_id::SourceId;
use crate::source::domain::value_objects::source_status::SourceStatus;

/// Command that requests an update of an existing source.
///
/// `source_type` is intentionally **not** part of the command — it is
/// immutable for the lifetime of a source. `updated_at` is generated by
/// [`SourceUpdater`] at execution time.
///
/// [`SourceUpdater`]: super::source_updater::SourceUpdater
pub struct UpdateSourceCommand {
    pub id: SourceId,
    pub status: SourceStatus,
    pub description: SourceDescription,
}

impl Command for UpdateSourceCommand {}
